"""Generate output examples given an input jsno files named examples.json  (generated by dump.py)."""

import json

OUTPUT_FILE = "examples.json"

if __name__ == "__main__":
    try:
        with open(OUTPUT_FILE, "r") as f:
            structure = json.load(f)
    except:
        structure = []

    print("%d test cases:" % len(structure))

    for expected, scores in structure:
        print("\nExpected: %d" % expected)
        print("Scores:")
        for width, score in scores:
            print("\t%03d: %f" % (width, score))
